# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(405, 472)
        MainWindow.setStyleSheet("background-color:gainsboro")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 10, 161, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.demoButton = QtWidgets.QPushButton(self.centralwidget)
        self.demoButton.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.demoButton.setObjectName("demoButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 330, 160, 89))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.cartesianCoordButtons = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.cartesianCoordButtons.setContentsMargins(0, 0, 0, 0)
        self.cartesianCoordButtons.setObjectName("cartesianCoordButtons")
        self.axeXbuttons = QtWidgets.QHBoxLayout()
        self.axeXbuttons.setObjectName("axeXbuttons")
        self.xpButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.xpButton.setObjectName("xpButton")
        self.axeXbuttons.addWidget(self.xpButton)
        self.xnButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.xnButton.setObjectName("xnButton")
        self.axeXbuttons.addWidget(self.xnButton)
        self.cartesianCoordButtons.addLayout(self.axeXbuttons)
        self.axeYbuttons = QtWidgets.QHBoxLayout()
        self.axeYbuttons.setObjectName("axeYbuttons")
        self.ypButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ypButton.setObjectName("ypButton")
        self.axeYbuttons.addWidget(self.ypButton)
        self.ynButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ynButton.setObjectName("ynButton")
        self.axeYbuttons.addWidget(self.ynButton)
        self.cartesianCoordButtons.addLayout(self.axeYbuttons)
        self.axeZbuttons = QtWidgets.QHBoxLayout()
        self.axeZbuttons.setObjectName("axeZbuttons")
        self.zpButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.zpButton.setObjectName("zpButton")
        self.axeZbuttons.addWidget(self.zpButton)
        self.znButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.znButton.setObjectName("znButton")
        self.axeZbuttons.addWidget(self.znButton)
        self.cartesianCoordButtons.addLayout(self.axeZbuttons)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 310, 131, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 300, 111, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 330, 160, 86))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.slidersArt = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.slidersArt.setContentsMargins(0, 0, 0, 0)
        self.slidersArt.setObjectName("slidersArt")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout.addWidget(self.horizontalSlider)
        self.slidersArt.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalLayout_3.addWidget(self.horizontalSlider_3)
        self.slidersArt.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_2)
        self.slidersArt.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 405, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SIMULADOR ROBOT DELTA"))
        self.demoButton.setText(_translate("MainWindow", "Demo"))
        self.xpButton.setText(_translate("MainWindow", "+X"))
        self.xnButton.setText(_translate("MainWindow", "-X"))
        self.ypButton.setText(_translate("MainWindow", "+Y"))
        self.ynButton.setText(_translate("MainWindow", "-Y"))
        self.zpButton.setText(_translate("MainWindow", "+Z"))
        self.znButton.setText(_translate("MainWindow", "-Z"))
        self.label_2.setText(_translate("MainWindow", "Movimientos cartesianos : "))
        self.label_3.setText(_translate("MainWindow", "Movmientos aticulares :"))
        self.label_4.setText(_translate("MainWindow", "q1"))
        self.label_6.setText(_translate("MainWindow", "q3"))
        self.label_5.setText(_translate("MainWindow", "q2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

